/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppRoot {}
  interface SubComponent {
    'reference': any;
    'textContent': string;
  }
}

declare global {


  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLSubComponentElement extends Components.SubComponent, HTMLStencilElement {}
  var HTMLSubComponentElement: {
    prototype: HTMLSubComponentElement;
    new (): HTMLSubComponentElement;
  };
  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement;
    'sub-component': HTMLSubComponentElement;
  }
}

declare namespace LocalJSX {
  interface AppRoot {}
  interface SubComponent {
    'onDeleted'?: (event: CustomEvent<any>) => void;
    'reference'?: any;
    'textContent'?: string;
  }

  interface IntrinsicElements {
    'app-root': AppRoot;
    'sub-component': SubComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'sub-component': LocalJSX.SubComponent & JSXBase.HTMLAttributes<HTMLSubComponentElement>;
    }
  }
}


